### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by Bazatree** [thestr4ng3r/mymcplus#5]
**1.** The "delete" command doesn't work properly. It doesn't delete saves and throws errors to the log.
![1 delete](https://user-images.githubusercontent.com/12977268/85322715-74430280-b4cf-11ea-9b70-13b5c1ffaff2.PNG)

**2.** If I want to import ".PSV" file, it doesn't show in the list by default. I have to use "All files" and only then I can select ".PSV" file. **Inconvenient.**
![2 psv 1](https://user-images.githubusercontent.com/12977268/85323465-b751a580-b4d0-11ea-8a4a-4779975b66b2.PNG)
![2 psv 2](https://user-images.githubusercontent.com/12977268/85323470-b9b3ff80-b4d0-11ea-84aa-a793fb350ffc.PNG)

**3.**  if I want to import ".max" format saves, then they will become corrupt or missing. 
_To avoid this, I have to convert them to ".cbs" with "PS2 Save Builder" and only then they will work._
![corrupt](https://user-images.githubusercontent.com/12977268/85322960-d7349980-b4cf-11ea-8198-d6bbcd5563da.PNG)
![cbs](https://user-images.githubusercontent.com/12977268/85324544-b588e180-b4d2-11ea-8fb1-e97c46e7db3c.PNG)

**Comment by thestr4ng3r** [comment]
Thanks for reporting, but please split these up into separate issues. For 1 and 3 please attach an example file since that will make fixing much easier.

**Comment by thestr4ng3r** [comment]
@Bazatree ping

**Comment by thestr4ng3r** [comment]
Closing because no response.

**Comment by Bazatree** [comment]
Done. 
Sorry for the slow response. I got the notification when you closed the issue.

**Comment by thestr4ng3r** [comment]
Thanks!
